# Generated by Django 3.1.7 on 2021-04-20 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=54)),
                ('date', models.DateField()),
                ('hero', models.CharField(max_length=34)),
                ('heroine', models.CharField(max_length=34)),
                ('ratings', models.IntegerField()),
            ],
        ),
    ]
